### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by wachub** [ethereum/pyethapp#72]
> I installed pyethapp using the pip installer.
> However  $ pyethapp run gives this error

File "/usr/local/lib/python2.7/dist-packages/ethereum/utils.py", line 6, in <module>
    from bitcoin import privtopub
ImportError: cannot import name privtopub

**Comment by panpilkarz** [comment]
It can't be reproduced among our team.

**Comment by edmundedgar** [comment]
I think the issue here is that pyethapp uses @vbuterin's library, formerly known as pybitcointools. This sometimes fights with Peter Todd's library, python-bitcoinlib, over who gets to be called "bitcoin". 

The path of minimal tinkering would be to either uninstall python-bitcoinlib (if you don't need it) or use pyethapp inside virtualenv and tell it to ignore the site version. This heads off other dependency version craziness too.

More suggestions here:
http://bitcoin.stackexchange.com/questions/36442/running-pybitcointools-python-bitcoinlib-concurrently

**Comment by konradkonrad** [comment]
+1 on using a virtualenv
@wachub have you had another take on this, does the issue still exist for you?
